# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0bcbf526e63709143dced5670e7b66e9d63efffaebeee9c44395f8061547add1975c04d0c38881a53d3eb82d14daefc1d4c8981ab404cfab505431078e3fb5c

test:
  secret_key_base: a9c5144da8f3b659511d15a2e54b4ff60b7a818aa18c443bd53c009fc148aed7c39cae0da3061977ddef87d9b755d957fd606d9f34d360228f729d27479f1ada

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
